[package]
name = "codeforces"
version = "0.1.0"
authors = ["Diego Niquefa <diego@valiu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
